### ISSUE TITLE
Docs updates megathread.

### ISSUE THREAD

**Issue by whmii** [thoughtbot/neat#488]
Neat 2.0 uses sass doc. There are going to be some issues where the guides are not comprehensive enough. I wanted to collect issues so that they can be consolidated simultaneously. When the new docs site 'goes live', I will post a link to it as well.
## Todo
- [x] [`Deefault` to `Default`](https://github.com/thoughtbot/neat/blob/7b53da0a27a7f5421d42e5afb55996343ce08081/core/neat/settings/_settings.scss#L7)
- [x] [`sass` to `Sass` in `neat-settings`](https://github.com/thoughtbot/neat/blob/7b53da0a27a7f5421d42e5afb55996343ce08081/core/neat/settings/_settings.scss#L19)
- [x] Write a general description of custom grid objects and how to use them
- [x] Installation instructions
- [ ] Something about upgrading

**Comment by whmii** [comment]
- [ ] https://github.com/thoughtbot/neat/blob/7b53da0a27a7f5421d42e5afb55996343ce08081/core/neat/settings/_settings.scss#L7 `Deefault` to `Default`
- [ ] https://github.com/thoughtbot/neat/blob/7b53da0a27a7f5421d42e5afb55996343ce08081/core/neat/settings/_settings.scss#L19 `sass` to `Sass`

**Comment by catherine-jones** [comment]
@whmii if you want someone to test out the doc for comprehension let me know going to be upgrading to Neat 2.0 next sprint hopefully.

**Comment by whmii** [comment]
Cool! @catherine-jones you can check out the new hotness at [http://neat.netlify.com](http://neat.netlify.com) (This domain will eventually be what replaces neat.bourbon.io).

I added some very basic installation instructions as well as an example page. However there is currently no "hey lets all have a big sit down and talk about how things work since things have changed and it's a little weird" page/section. 

The ROI on upgrading large projects from 1.X to 2.0 will likely be tough considering the amount of front end code that would need to be changed. However, for new projects or those that only use Neat to a minor extent now, using Neat 2.0 has some real benefits both in its flexibility as well as its over ease of use and some major quality of life improvements.

**I would love any feedback you have on the experience. Feel free to post issues here or over at [https://github.com/thoughtbot/neat.bourbon.io](https://github.com/thoughtbot/neat.bourbon.io), wherever is more relevent.**

**Comment by haydenhancock** [comment]
@whmii I am using Chrome (53.0.2785.116 m) to view the docs on the domain you mentioned above and I am seeing a scroll bar appear when scrolling down. This doesn't seem to happen in IE (11.0.10240.17022).

**Comment by MikeHarrison** [comment]
Happy to look through the docs. Spotted a typo - `Grid containter` instead of `Grid container`. Where should I post this sort of feedback?

**Comment by whmii** [comment]
Thanks for the heads up. Any comments on the documentation can be posted here for now. The site itself has its own repository, but all the content of the documentation is pulled from this one.

**Comment by whmii** [comment]
Needs update to `Custom grids` docs where citation is incorrect and reffs `grid-span` instead of `grid-column`

**Comment by whmii** [comment]
done… for now
